### ISSUE TITLE
迁移春松客服文档到新的站点

### ISSUE THREAD

**Issue by hailiang-wang** [cskefu/cskefu-docs#1]
当前站点在：

https://docs.chatopera.com/products/cskefu/index.html

当前站点源码在：

https://github.com/chatopera/docs/tree/master/docfx_project/products/cskefu

需要：

1）独立为春松客服的专有站点

2）使用春松客服的域名 cskefu.com

3）公开协作文档

**Comment by hailiang-wang** [comment]
[divio-documentation-system-readthedocs-hosted-com-en-latest.pdf](https://github.com/cskefu/cskefu-docs/files/9442536/divio-documentation-system-readthedocs-hosted-com-en-latest.pdf)

另外，还应该考虑在未来重构文档中心的内容，文档系统使用：divio docs system

![image](https://user-images.githubusercontent.com/3538629/187149736-479b64c5-85ad-4169-bffe-65f354e25b38.png)


案例，many of them, just one for reference.
https://wechaty.js.org/

**Comment by hailiang-wang** [comment]
@SAMZONG 

现在春松客服的文档 Markdown，Assets 在这里

https://github.com/chatopera/docs/tree/master/docfx_project/products/cskefu

![image](https://user-images.githubusercontent.com/3538629/187194094-3ddc89f7-8996-42eb-9863-9990d835b372.png)

**Comment by SAMZONG** [comment]
get it.

**Comment by SAMZONG** [comment]
@hailiang-wang Hi 文档已经迁移完成，预览地址： https://cskefu.github.io/cskefu-docs/

> 存在一些 broken link, 后续慢慢修复.

**Comment by hailiang-wang** [comment]
看起来很棒，现在是向 main 分支提交，就自动构建为 gh-pages 分支吗？

![image](https://user-images.githubusercontent.com/3538629/189511362-fd3314d0-ad2b-4bf7-b680-00fad874d897.png)

**Comment by hailiang-wang** [comment]
构建和 hosting，见 https://github.com/cskefu/cskefu-docs/issues/3
今天我弄一下。

@SAMZONG

**Comment by SAMZONG** [comment]
> 

是的，通过main 分支更新，会自动触发 构建 github-pages。
同时提供了 pr 时的 检测能力。
