### ISSUE TITLE
文档中心支持切换版本

### ISSUE THREAD

**Issue by hailiang-wang** [cskefu/cskefu-docs#12]
目前，春松客服有多个版本，每个版本的文档宜在文档中心可切换。

![image](https://user-images.githubusercontent.com/3538629/195258766-2dbc1396-594c-4de8-9b8b-088269e779e1.png)

类似于 ElasticSearch 中

![image](https://user-images.githubusercontent.com/3538629/195258980-400c3023-a186-411c-beb0-8f5d12485c73.png)

那么每个版本可以作为一个独立的目录存放 markdown 在 docs 中，图片等 media 文件可共用一个目录，在添加 media 时，不覆盖旧的文件。

**Comment by SAMZONG** [comment]
> 

@hailiang-wang 我做过这方面的实现，利用咱们现有的文档站框架； 可以参考下我参与实现的一个 karmada.io

我可以来处理这件事情

**Comment by hailiang-wang** [comment]
@SAMZONG 文档中心支持分支有进展了吗？我有几点设想：

## landing page

landing page 页面可以是一样的，不同版本共用。

![sceenshoot_20221201082337](https://user-images.githubusercontent.com/3538629/204936368-cece3d9f-8f19-48d1-82bc-5e826a6f7163.png)

## 分支对应

从一级菜单进入【文档中心】后，支持切换，切换目录可按照【master】【develop】与 cskefu/cskefu 的两个主要分支对应。

![sceenshoot_20221201082416](https://user-images.githubusercontent.com/3538629/204936436-7dcec187-13d7-4d1c-8ce9-0f1ec150df13.png)

在 cskefu/cskefu-docs 中，则让 master 和 develop 对应到两个文件夹，以方便撰写。

**Comment by hailiang-wang** [comment]
使用如下连个 版本：

* Next, 开发中的大版本，目前是 v8
* v7, 当前稳定版本
