### ISSUE TITLE
服务发布和域名解析

### ISSUE THREAD

**Issue by hailiang-wang** [cskefu/cskefu-docs#2]
## 前置条件

代码库提供 build docker 镜像脚本和 docker-compose.yml 文件后。

## 发布

* 发布到机器
* 更新域名解析

**Comment by hailiang-wang** [comment]
完成域名配置：

https://docs.cskefu.com/ --> https://cskefu.github.io/cskefu-docs/

**Comment by SAMZONG** [comment]
是否可以直接把域名 docs.cskefu.com CNAME 到 cskefu.github.io

**Comment by hailiang-wang** [comment]
最合理方案是这样。几年前用阿里云 CNAME 解析到这个地址，说是 github.io 没有备案，不能 CNAME。
这次再试试。
有一个准备工作，需要在 repo 上也加入 CNAME 文件吧？

![image](https://user-images.githubusercontent.com/3538629/189554377-523f2805-1053-429e-9cd7-f78c2f966476.png)

阿里云解析完成变更了。

![image](https://user-images.githubusercontent.com/3538629/189554473-23d20e12-daba-4418-9765-0fb92c1b484b.png)

**Comment by hailiang-wang** [comment]
# repo pages 配置

![image](https://user-images.githubusercontent.com/3538629/189554568-ead067c2-622b-4e52-be71-4fc5ded76a70.png)

# 访问提示

![image](https://user-images.githubusercontent.com/3538629/189554548-7cac8eac-4a42-4fac-8419-54e761594261.png)

**Comment by hailiang-wang** [comment]
完成服务发布，地址为：

https://docs.cskefu.com

**Comment by hailiang-wang** [comment]
目前方案没有使用 GitHub Pages
