### ISSUE TITLE
文档中心自动构建

### ISSUE THREAD

**Issue by hailiang-wang** [cskefu/cskefu-docs#3]
## 前置条件

依赖于 #2 

## CI & CD

GitHub Repo push 发生后，自动构建，和发布。
并且将 status 更新到 github repo commit 上，显示为绿色对号，代表自动发布完成。

**Comment by hailiang-wang** [comment]
基于 https://github.com/cskefu/cskefu-docs/issues/1 中 HTTPs 配置，需要一个证书。
这样的话，还是用 docs 构建为 static 文件，host 在一台主机上，使用 `let's encrypt` 实现更快。
同时可提升国内用户的访问速度。

**Comment by Kaifuny** [comment]
> 基于 #1 中 HTTPs 配置，需要一个证书。 这样的话，还是用 docs 构建为 static 文件，host 在一台主机上，使用 `let's encrypt` 实现更快。 同时可提升国内用户的访问速度。

使用github page 做文档站点吗？用 cloudflare cdn 应该是默认添加 https 了

**Comment by hailiang-wang** [comment]
因为要使用自定义域名，所以服务 hosting 在一台服务器，做了 `let's encrypt` SSL。

**当 https://github.com/cskefu/cskefu-docs/ 的 main 分支推送代码后，https://docs.cskefu.com 将会在 5mins 内刷新。**

![image](https://user-images.githubusercontent.com/3538629/189567969-6389ecb9-5287-4b38-9151-d9f067a57b9f.png)

![image](https://user-images.githubusercontent.com/3538629/189568012-eb543d05-edb5-4adc-b791-b68d54187b81.png)

**Comment by SAMZONG** [comment]
github pages 会自动为域名提供 HTTPS 证书，所以只需要进行 CNAME 即可，当然 github pages 因为 hosting 在国外，所以访问速度上会较弱；迁移到国内是个不错的选择。

赞同你的做法。
